### PR TITLE
Update v3 map to incorporte Strat Bombing attribute

### PR DESCRIPTION
**Pull request by simon33-2**
Not ordered.

### CODE REVIEW

**Comment by simon33-2** [comment]
Ok, I think the properties are more correctly ordered.

**Comment by DanVanAtta** [comment]
The ordering really should not matter. However it is good practice to group related options together.

I tested this out, it does not seem to fix SBR, damage was still allocated to the player's PU's, not to the factory.

**Comment by simon33-2** [comment]
I've just tested it in both 1941 and 1942. Are you sure you got the update? The triplea_maps.yaml has not been updated so you need to force the update.

And in fact, the PR has not been merged so you need to grab it from my fork.

**Comment by simon33-2** [comment]
Oops, I was looking at v3 for some reason. It seems that somehow the v3 map was omitted from some of the other updates I did. Also can't recall why I would have added the additional attribute. Maybe you got a java error.

**Comment by simon33-2** [comment]
@DanVanAtta 
Can we merge this one now?

**Comment by DanVanAtta** [comment]
Tested this update out for v3 - damage is done to the factory now and does not subtract PUs. GJ
I added a commit to fix up the formatting as well.

**Pull request merged**
